### ISSUE TITLE
Create pcb for 2015 base station

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-pcb#15]
This won't be anything fancy, just something simple so we don't have to use in place of a breadboard.

cc @jjones646

**Comment by jjones646** [comment]
probably will want to support 2 radios on separate spi busses.

**Comment by justbuchanan** [comment]
Good call.  We talked about doing that before, but I had completely forgotten about it.

**Comment by justbuchanan** [comment]
@jjones646 any idea where I can find an eagle library for this part?

http://www.digikey.com/product-search/en/connectors-interconnects/rectangular-board-to-board-connectors-headers-male-pins/1442672?k=609%203175%20nd

**Comment by justbuchanan** [comment]
Also, what's the best way to show connections to the mbed in the schematic?  The board will have the female headers for the mbed to plug into, but it would be nice in the schematic to show the pinout of the mbed.  I guess I could just add the headers to the schematic and label the relevant pins, but I'm not sure if there's a better way to use the mbed.

**Comment by jjones646** [comment]
make it :smile:. It's a super easy part, just make the pads shorter than what the datasheet recommends...

There should be an mbed library part in the repo somehwere

**Comment by justbuchanan** [comment]
Sounds good, I should be able to handle that.

Yeah I see the mbed library in this repo.  My question was more of should I put the headers in the schematic or the mbed itself?  Or both?  The pcb will just have two rows of headers mounted on it.

**Comment by jjones646** [comment]
Just the mbed in the schematic should work out fine.
